apiVersion: apps/v1 
kind: Deployment
metadata:
  name: metal
  labels:
    app: metal
spec:
  selector:
    matchLabels:
      app: metal
  replicas: 1
  template:
    metadata:
      labels:
        app: metal
    spec:
      containers:
      - name: metal
        image: metal:1.0
        args: ["-conf=/conf/conf.toml"]
        imagePullPolicy: Always
        ports:
          - containerPort: 9030
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: conf-vol
          mountPath: /conf
        resources:
          requests: 
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "100m"
      volumes:
        - name: conf-vol
          configMap:
            name: metal-config
